[workspace]
name = "robostack"
description = "Development environment for RoboStack ROS packages"
channels = ["https://prefix.dev/conda-forge"]
# platforms = ["osx-arm64"]
# platforms = ["linux-64", "osx-64", "osx-arm64", "linux-aarch64"]
platforms = ["linux-aarch64"]

# This will automatically activate the ros workspace on activation
# [target.win.activation]
# scripts = ["install/setup.bat"]

[target.unix.activation]
# For activation scripts, we use bash for Unix-like systems
scripts = ["install/setup.bash"]

# To build you can use - `pixi run -e <ros distro> build <Any other temporary args>`
# [feature.build.target.win-64.tasks]
# build = "colcon build --merge-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

[feature.build.target.unix.tasks]
build = "colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

# Dependencies used by all environments
[dependencies]
swig = "*"
python = "*"
# Build tools
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
# ROS specific tools
rosdep = "*"
colcon-common-extensions = "*"

[pypi-dependencies]
pigpio = "*"
pyserial = "*"

[target.linux.dependencies]
libgl-devel = "*"

# Define all the different ROS environments
# Each environment corresponds to a different ROS distribution
# and can be activated using the `pixi run/shell -e <environment>` command.
[environments]
# On your development PC/laptop (full desktop + sim tools)
humble-host = { features = ["humble", "host", "build"] }
# On the actual robot (minimal)
humble-robot = { features = ["humble", "robot", "build"] }

### ROS Humble ###
[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.host.dependencies]
ros-humble-desktop = "*"
ros-humble-launch = "*"
ros-humble-slam-toolbox = "*"
ros-humble-navigation2 = "*"
ros-humble-nav2-bringup = "*"
ros-humble-ros-gz = "*"
ros-humble-ros-gz-bridge = "*"
ros-humble-ros-gz-sim = "*"
ros-humble-ros2-control = "*"
ros-humble-gz-ros2-control = "*"
ros-humble-gazebo-ros = "*"
ros-humble-gazebo-ros-pkgs = "*"
ros-humble-rmw-cyclonedds-cpp = "*"
ros-humble-xacro = "*"
ros-humble-joint-state-publisher-gui = "*"
ros-humble-demo-nodes-cpp = "*"

[feature.robot.dependencies]
ros-humble-ros-base = "*"
ros-humble-launch = "*"
ros-humble-slam-toolbox = "*"
ros-humble-navigation2 = "*"
ros-humble-nav2-bringup = "*"
ros-humble-ros2-control = "*"
ros-humble-xacro = "*"
ros-humble-joint-state-publisher = "*"
ros-humble-nav-msgs = "*"
ros-humble-teleop-twist-keyboard = "*"
ros-humble-rmw-cyclonedds-cpp = "*"
ros-humble-demo-nodes-cpp = "*"