/**:
  ros__parameters:
    pwm_pin: 12
    pwm_freq: 1000
    pwm_duty: 70
    port: /dev/ttyUSB0
    baud: 115200
    min_dist_mm: 200
    max_dist_mm: 6000
    frame_id: laser_frame
    scan_topic: scan